import dotenv from "dotenv";
dotenv.config();


enum ENVIRONMENT_VARIABLES {
  SERVER_PORT = "SERVER_PORT",
  DATABASE_NAME = "DATABASE_NAME",
  DATABASE_USERNAME = "DATABASE_USERNAME",
  DATABASE_PASSWORD = "DATABASE_PASSWORD",
  DATABASE_HOST = "DATABASE_HOST",
  DATABASE_PORT = "DATABASE_PORT",
  NODE_ENV = "NODE_ENV",
  GATEWAY_SECRET_KEY= 'GATEWAY_SECRET_KEY'

}

function getEnv(variableName: ENVIRONMENT_VARIABLES) {
  const envKey = ENVIRONMENT_VARIABLES[variableName];
  const foundEnv = process.env[envKey];
  const message = `${envKey} was not found`;
  if (!foundEnv) {
    console.log(message);
    throw Error(message);
  }
  return foundEnv;
}

export const APP_CONFIGS = {
  SERVER_PORT: getEnv(ENVIRONMENT_VARIABLES.SERVER_PORT),
  DATABASE_NAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_NAME),
  DATABASE_USERNAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_USERNAME),
  DATABASE_PASSWORD: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PASSWORD),
  DATABASE_HOST: getEnv(ENVIRONMENT_VARIABLES.DATABASE_HOST),
  DATABASE_PORT: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PORT),
  NODE_ENV: getEnv(ENVIRONMENT_VARIABLES.NODE_ENV),
  GATEWAY_SECRET_KEY: getEnv(ENVIRONMENT_VARIABLES.GATEWAY_SECRET_KEY)
};
